Repository gtk-rs/gtk4-rs, pull requests merged in 2022-11, with the labels that each got.

#1186 gsk: Export builders module
  gsk4/src/builders.rs
  gsk4/src/lib.rs
Labels: gsk, needs-backport

#1179 macros: Allow using re-exports of gtk
  gtk4-macros/src/util.rs
Labels: needs-backport

#1188 Update dependencies
  gdk4-win32/Cargo.toml
  gtk4-macros/Cargo.toml
Labels: needs-backport

#1192 gtk4: use impl_offset() for calculating template child offset
  gtk4/src/subclass/widget.rs
Labels: needs-backport

#1178 Added Libxml, Librsvg, Gettext and Libadwaita demo
  book/src/installation_windows.md
  book/src/libadwaita.md
Labels: book
